export const SET_IMAGES_IS_LOADING = "SET_IMAGES_IS_LOADING";
export const GET_IMAGES = "GET_IMAGES";
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGES_FAIL = "GET_IMAGES_FAIL";